server:
  port: 7070

spring:
  datasource:
    username: root
    password: wsly1994
    url: jdbc:mysql://114.115.158.243:23333/msp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.brank.chuyiting.chuyitingmsp.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
